### ISSUE TITLE
After a while of using it, recipes cannot be added anymore

### ISSUE THREAD

**Issue by saschaheylik** [guyo13/free-macro-tracker#1]
Hi, I could use the app and add recipes for some time, but now not anymore. When creating a new recipes and pressing save simply nothing happens.

Do you still maintain this project? Would you be interested in details to reproduce the bug or not anymore?

Best regards

**Comment by guyo13** [comment]
Hi, I’m still maintaining the project, if you can add steps to reproduce the issue I’ll look into it. On which platform are you running the app?

**Comment by saschaheylik** [comment]
Sent you the details via email since it includes private data.

**Comment by guyo13** [comment]
After reproducing the issue with @saschaheylik it seems that not all of the required fields were filled and therefore the recipe was not saved. We should notify the user with a relevant message when failing to add a recipe.
We'll track this issue in #2
